services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: run

  jacoco:
    build:
      context: .
      dockerfile: Dockerfile
      target: jacoco

  tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: tests

  docs:
    build:
      context: .
      dockerfile: Dockerfile
      target: docs
    volumes:
      - ./proxy/auth-docs/.htpasswd:/usr/local/apache2/conf/.htpasswd
      - ./proxy/conf/httpd-auth.conf:/usr/local/apache2/conf/httpd-auth.conf

  proxy:
    image: ubuntu/nginx
    container_name: proxy_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/conf/nginx.conf:etc/nginx/nginx.conf
      - ./proxy/certs:etc/nginx/certs
    restart: always
    depends_on:
      - jacoco
      - tests
      - docs
      - app
